image: maven:3-jdk-8-alpine

cache:
  paths:
    - .m2/

stages:
  - unit_test
  - integration_test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

maven_test:
  stage: unit_test
  script:
  - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - target/

maven_verify:
  stage: integration_test
  only:
    - master
    - develop
  script:
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    paths:
      - target/*.jar
