image: maven:3-jdk-8-alpine

cache:
  paths:
    - .m2/

stages:
  - unit_test
  - integration_test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

maven_test:
  stage: unit_test
  script:
  - mvn $MAVEN_CLI_OPTS test
  - cat ./target/site/jacoco/index.html && echo
  artifacts:
    paths:
      - target/
  coverage: '/Total.*?([0-9]{1,3})%/'

.maven_verify: &maven_verify
  stage: integration_test
  script:
    - mvn $MAVEN_CLI_OPTS verify

maven_verify:develop:
  <<: *maven_verify
  only:
    - master
    - develop
  artifacts:
    paths:
      - target/

maven_verify:branch:
  <<: *maven_verify
  except:
    - master
    - develop
  when: manual
